server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krkoknj/git-remote-yml
#          uri: file://D:\work\git-local-repo
#          uri: file://D:\study\git-local-repo